
PADDING_BORDER = 10

TILE_SIZE = 50
TILE_GAP = 3

CHARGE_STATION_HEIGHT = 58
SHELF_HEIGHT = 74
SHELF_TOP_HEIGHT = 36
GAME_WIDTH = 704 + PADDING_BORDER     #22 cols
GAME_HEIGHT = 512 + PADDING_BORDER    #15 rows
ROBOT_DISTANCE = 5

# warehouse layout
NUMBER_OF_ROBOTS = 5


# robot position and size
ROBOT_X = PADDING_BORDER + 5
ROBOT_Y = PADDING_BORDER + 5
ROBOT_WIDTH = 40
ROBOT_LENGTH = 48
ROBOT_VELOCITY_X = 3
ROBOT_VELOCITY_Y = 3

# environment variables
FRICTION = 0.4
